version: '3'
services:
  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    networks:
      - app-network
    volumes:
      - ./:/var/www/html
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    depends_on:
      - php
  php:
    image: php:8.1.0-fpm
    ports:
      - '9000:9000'
    networks:
      - app-network
    volumes:
      - ./:/var/www/html

networks:
  app-network:
    driver: bridge